config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pics#index"
  resources :pics
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/pic.rb
class Pic < ApplicationRecord
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :pics
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pics_controller.rb
class PicsController < ApplicationController
	before_action :find_pic, only: [:show, :edit, :update, :destroy]

	def index
		@pics = Pic.all.order("created_at DESC")
	end

	def show
		
	end

	def new
		@pic =  current_user.pics.build
	end

	def create
		@pic = current_user.pics.build(pic_params)
		if @pic.save
			redirect_to @pic, notice: "Yes It was posted!"
		else
			render 'new'
		end
	end

	def edit
		
	end

	def update
		if @pic.update(pic_params)
			redirect_to @pic, notice:"Congrats! Pic was updated!"
		else
			render 'edit'
		end
	end

	def destroy
		@pic.destroy
		redirect_to root_path, notice: "Pic was successfully deleted"
	end

	private
		def pic_params
			# binding.pry

			params.require(:pic).permit(:title, :description)
			# params.permit(:title, :description)
		end

		def find_pic
			@pic = Pic.find(params[:id])
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pics_helper.rb
module PicsHelper
end

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Insta
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_importmap_tags
  %body
    %nav.nav-bar.navbar-inverse
      .container
        .navbar-brand= link_to "INsta", root_path
        - if user_signed_in?
          %ul.nav.navbar-nav.navbar-left
            %li= link_to "Gram It!", new_pic_path
            %li= link_to "Settings", edit_user_registration_path
            %li= link_to "Sign Out", destroy_user_session_path, data: { turbo_method: :delete }
        - else
          %ul.nav.navbar-nav.navbar-left
            %li= link_to "Join", new_user_registration_path
            %li= link_to "Login", new_user_session_path

    .container
      - flash.each do |name, msg|
        = content_tag :div, msg, class: "alert alert-info"
      = yield

app/views/pics/_form.html.haml
= simple_form_for @pic, html: { multipart: true} do |f|
	- if @pic.errors.any?
		#errors
			%h2
			= pluralize(@pic.errors.count, 'error')
			prevented this pic from saving!
			%ul
				- @pic.errors.full_messages.each do |msg|
					%li= msg
	.form-group
		= f.input :title, input_html: { class: "form-control"}
	.form-group
		= f.input :description, input_html: { class: "form-control"}
	= f.button :submit, class: "btn btn-info"

app/views/pics/edit.html.haml
#edit_page.col-md-8.col-md-offset-2
	.row
		.panel.panel-default
			.panel-heading
				%h1 Fix Pic
			.panel-body
				= render 'form'

app/views/pics/index.html.haml
- @pics.each do |pic|
	%h2= link_to pic.title, pic

app/views/pics/new.html.haml
.col-md-8.col-md-offset-2
	.row
		.panel.panel-default
			.panel-heading
				%h1 Post Pic
			.panel-body
				= render 'form'

app/views/pics/show.html.haml
%h1= @pic.title
%p= @pic.description
%p Pic By
= @pic.user.email 
%br
= link_to "Back", root_path
= link_to "Edit", edit_pic_path
= link_to "Delete", pic_path, data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } 